// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/policy.proto

package v1

import (
	v1 "github.com/in-toto/attestation/go/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicySet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the policySet identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Meta holds the PolicySet metadata informartion
	Meta *PolicySetMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	// Common groups the common data elements to be share by all the
	// policies in the set.
	Common *PolicySetCommon `protobuf:"bytes,3,opt,name=common,proto3" json:"common,omitempty"`
	// Policies is the list of policies grouped in the PolicySet
	Policies []*Policy `protobuf:"bytes,4,rep,name=policies,proto3" json:"policies,omitempty"`
	// Chain is the evidence chain to compute a set of subjects to which
	// al the policies will apply.
	Chain []*ChainLink `protobuf:"bytes,5,rep,name=chain,proto3" json:"chain,omitempty"`
	// PolicyGroup definitions
	Groups        []*PolicyGroup `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySet) Reset() {
	*x = PolicySet{}
	mi := &file_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySet) ProtoMessage() {}

func (x *PolicySet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySet.ProtoReflect.Descriptor instead.
func (*PolicySet) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PolicySet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicySet) GetMeta() *PolicySetMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PolicySet) GetCommon() *PolicySetCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *PolicySet) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *PolicySet) GetChain() []*ChainLink {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *PolicySet) GetGroups() []*PolicyGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type PolicySetMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       string                 `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Enforce       string                 `protobuf:"bytes,5,opt,name=enforce,proto3" json:"enforce,omitempty"`
	Frameworks    []*FrameworkRef        `protobuf:"bytes,6,rep,name=frameworks,proto3" json:"frameworks,omitempty"`
	Origin        *v1.ResourceDescriptor `protobuf:"bytes,7,opt,name=origin,proto3,oneof" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySetMeta) Reset() {
	*x = PolicySetMeta{}
	mi := &file_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySetMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySetMeta) ProtoMessage() {}

func (x *PolicySetMeta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySetMeta.ProtoReflect.Descriptor instead.
func (*PolicySetMeta) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *PolicySetMeta) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *PolicySetMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PolicySetMeta) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *PolicySetMeta) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicySetMeta) GetEnforce() string {
	if x != nil {
		return x.Enforce
	}
	return ""
}

func (x *PolicySetMeta) GetFrameworks() []*FrameworkRef {
	if x != nil {
		return x.Frameworks
	}
	return nil
}

func (x *PolicySetMeta) GetOrigin() *v1.ResourceDescriptor {
	if x != nil {
		return x.Origin
	}
	return nil
}

// FrameworkRef is a reference to a security framework. The reference binds
// the controls tested by each the policy to the the framework definition.
type FrameworkRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                 // String identifier for the framework
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`             // Security framework name
	Definition    *v1.ResourceDescriptor `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"` // Link to the framework definition
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameworkRef) Reset() {
	*x = FrameworkRef{}
	mi := &file_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameworkRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameworkRef) ProtoMessage() {}

func (x *FrameworkRef) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameworkRef.ProtoReflect.Descriptor instead.
func (*FrameworkRef) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *FrameworkRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FrameworkRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FrameworkRef) GetDefinition() *v1.ResourceDescriptor {
	if x != nil {
		return x.Definition
	}
	return nil
}

type PolicySetCommon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []*Identity            `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	References    []*PolicyRef           `protobuf:"bytes,2,rep,name=references,proto3" json:"references,omitempty"`
	Context       map[string]*ContextVal `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySetCommon) Reset() {
	*x = PolicySetCommon{}
	mi := &file_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySetCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySetCommon) ProtoMessage() {}

func (x *PolicySetCommon) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySetCommon.ProtoReflect.Descriptor instead.
func (*PolicySetCommon) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *PolicySetCommon) GetIdentities() []*Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *PolicySetCommon) GetReferences() []*PolicyRef {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *PolicySetCommon) GetContext() map[string]*ContextVal {
	if x != nil {
		return x.Context
	}
	return nil
}

type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        *PolicyRef             `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Meta          *Meta                  `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Context       map[string]*ContextVal `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Chain         []*ChainLink           `protobuf:"bytes,5,rep,name=chain,proto3" json:"chain,omitempty"`
	Identities    []*Identity            `protobuf:"bytes,6,rep,name=identities,proto3" json:"identities,omitempty"`
	Predicates    *PredicateSpec         `protobuf:"bytes,7,opt,name=predicates,proto3" json:"predicates,omitempty"`
	Transformers  []*Transformer         `protobuf:"bytes,8,rep,name=transformers,proto3" json:"transformers,omitempty"`
	Tenets        []*Tenet               `protobuf:"bytes,9,rep,name=tenets,proto3" json:"tenets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *Policy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Policy) GetSource() *PolicyRef {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Policy) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Policy) GetContext() map[string]*ContextVal {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Policy) GetChain() []*ChainLink {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *Policy) GetIdentities() []*Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *Policy) GetPredicates() *PredicateSpec {
	if x != nil {
		return x.Predicates
	}
	return nil
}

func (x *Policy) GetTransformers() []*Transformer {
	if x != nil {
		return x.Transformers
	}
	return nil
}

func (x *Policy) GetTenets() []*Tenet {
	if x != nil {
		return x.Tenets
	}
	return nil
}

type PolicyRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Identity      *Identity              `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	Location      *v1.ResourceDescriptor `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRef) Reset() {
	*x = PolicyRef{}
	mi := &file_v1_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRef) ProtoMessage() {}

func (x *PolicyRef) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRef.ProtoReflect.Descriptor instead.
func (*PolicyRef) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{5}
}

func (x *PolicyRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyRef) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyRef) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *PolicyRef) GetLocation() *v1.ResourceDescriptor {
	if x != nil {
		return x.Location
	}
	return nil
}

type ChainLink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*ChainLink_Predicate
	Source        isChainLink_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainLink) Reset() {
	*x = ChainLink{}
	mi := &file_v1_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainLink) ProtoMessage() {}

func (x *ChainLink) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainLink.ProtoReflect.Descriptor instead.
func (*ChainLink) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{6}
}

func (x *ChainLink) GetSource() isChainLink_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ChainLink) GetPredicate() *ChainedPredicate {
	if x != nil {
		if x, ok := x.Source.(*ChainLink_Predicate); ok {
			return x.Predicate
		}
	}
	return nil
}

type isChainLink_Source interface {
	isChainLink_Source()
}

type ChainLink_Predicate struct {
	Predicate *ChainedPredicate `protobuf:"bytes,1,opt,name=predicate,proto3,oneof"` // ChainedOutput output = 2;
}

func (*ChainLink_Predicate) isChainLink_Source() {}

// Meta contains information about the policy itself
type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       string                 `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AssertMode    string                 `protobuf:"bytes,3,opt,name=assert_mode,json=assertMode,proto3" json:"assert_mode,omitempty"`
	Controls      []*Control             `protobuf:"bytes,4,rep,name=controls,proto3" json:"controls,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Enforce       string                 `protobuf:"bytes,6,opt,name=enforce,proto3" json:"enforce,omitempty"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expiration,proto3,oneof" json:"expiration,omitempty"`
	Origin        *v1.ResourceDescriptor `protobuf:"bytes,8,opt,name=origin,proto3,oneof" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_v1_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{7}
}

func (x *Meta) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Meta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Meta) GetAssertMode() string {
	if x != nil {
		return x.AssertMode
	}
	return ""
}

func (x *Meta) GetControls() []*Control {
	if x != nil {
		return x.Controls
	}
	return nil
}

func (x *Meta) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Meta) GetEnforce() string {
	if x != nil {
		return x.Enforce
	}
	return ""
}

func (x *Meta) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *Meta) GetOrigin() *v1.ResourceDescriptor {
	if x != nil {
		return x.Origin
	}
	return nil
}

// Identity captures a signer identity. An identity can one of:
//
//	a) A sigstore identity
//	b) A key
//	c) A reference to an identity defined outside the policy
type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sigstore      *IdentitySigstore      `protobuf:"bytes,2,opt,name=sigstore,proto3,oneof" json:"sigstore,omitempty"`
	Key           *IdentityKey           `protobuf:"bytes,3,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Ref           *IdentityRef           `protobuf:"bytes,4,opt,name=ref,proto3,oneof" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_v1_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{8}
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetSigstore() *IdentitySigstore {
	if x != nil {
		return x.Sigstore
	}
	return nil
}

func (x *Identity) GetKey() *IdentityKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Identity) GetRef() *IdentityRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

// Control is a mapping tying the policy to an framework control
type Control struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Class         string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Framework     string                 `protobuf:"bytes,3,opt,name=framework,proto3" json:"framework,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_v1_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{9}
}

func (x *Control) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Control) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Control) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *Control) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// IdentitySigstore represents the identity data in a Fulcio cert.
type IdentitySigstore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          *string                `protobuf:"bytes,1,opt,name=mode,proto3,oneof" json:"mode,omitempty"`   // exact | regexp
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`     // https://accounts.google.com
	Identity      string                 `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"` //  "identity": "puerco@gmail.com"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentitySigstore) Reset() {
	*x = IdentitySigstore{}
	mi := &file_v1_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySigstore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySigstore) ProtoMessage() {}

func (x *IdentitySigstore) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySigstore.ProtoReflect.Descriptor instead.
func (*IdentitySigstore) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{10}
}

func (x *IdentitySigstore) GetMode() string {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return ""
}

func (x *IdentitySigstore) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *IdentitySigstore) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

// IdentityKey registers the data of a key used to sign attestations.
type IdentityKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // Key ID
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // Identity type
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // Public key data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityKey) Reset() {
	*x = IdentityKey{}
	mi := &file_v1_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityKey) ProtoMessage() {}

func (x *IdentityKey) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityKey.ProtoReflect.Descriptor instead.
func (*IdentityKey) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{11}
}

func (x *IdentityKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdentityKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IdentityKey) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// IdentityRef represents an identity defined outside of the policy. Most commonly
// these identities will be defined at the policy set level to have a common
// definition that can be reused by all policies in a set.
type IdentityRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityRef) Reset() {
	*x = IdentityRef{}
	mi := &file_v1_policy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRef) ProtoMessage() {}

func (x *IdentityRef) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRef.ProtoReflect.Descriptor instead.
func (*IdentityRef) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{12}
}

func (x *IdentityRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ContextVal defines a contextual value needed by a policy. Context values
// are defined from external sources at runtime and if required will cause the
// policy to fail if unset.
type ContextVal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Required      *bool                  `protobuf:"varint,2,opt,name=required,proto3,oneof" json:"required,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Default       *structpb.Value        `protobuf:"bytes,4,opt,name=default,proto3,oneof" json:"default,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextVal) Reset() {
	*x = ContextVal{}
	mi := &file_v1_policy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextVal) ProtoMessage() {}

func (x *ContextVal) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextVal.ProtoReflect.Descriptor instead.
func (*ContextVal) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{13}
}

func (x *ContextVal) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContextVal) GetRequired() bool {
	if x != nil && x.Required != nil {
		return *x.Required
	}
	return false
}

func (x *ContextVal) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ContextVal) GetDefault() *structpb.Value {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *ContextVal) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// The error structure is returned when a policy is evaluated successfully but
// the evaluation fails.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message contains the condition that failed to be met, causing the policy to fail.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Guidance is an optional text record that is surfaced to the user with
	// suggestions to make the policy evaluation pass.
	Guidance      string `protobuf:"bytes,2,opt,name=guidance,proto3" json:"guidance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_v1_policy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{14}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetGuidance() string {
	if x != nil {
		return x.Guidance
	}
	return ""
}

// Este hay que arreglarlo
type Transformer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transformer) Reset() {
	*x = Transformer{}
	mi := &file_v1_policy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transformer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transformer) ProtoMessage() {}

func (x *Transformer) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transformer.ProtoReflect.Descriptor instead.
func (*Transformer) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{15}
}

func (x *Transformer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PredicateSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []string               `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredicateSpec) Reset() {
	*x = PredicateSpec{}
	mi := &file_v1_policy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredicateSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredicateSpec) ProtoMessage() {}

func (x *PredicateSpec) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredicateSpec.ProtoReflect.Descriptor instead.
func (*PredicateSpec) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{16}
}

func (x *PredicateSpec) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *PredicateSpec) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Tenet
type Tenet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Runtime       string                 `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Predicates    *PredicateSpec         `protobuf:"bytes,4,opt,name=predicates,proto3" json:"predicates,omitempty"`
	Outputs       map[string]*Output     `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         *Error                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Assessment    *Assessment            `protobuf:"bytes,8,opt,name=assessment,proto3" json:"assessment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenet) Reset() {
	*x = Tenet{}
	mi := &file_v1_policy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenet) ProtoMessage() {}

func (x *Tenet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenet.ProtoReflect.Descriptor instead.
func (*Tenet) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{17}
}

func (x *Tenet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenet) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Tenet) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Tenet) GetPredicates() *PredicateSpec {
	if x != nil {
		return x.Predicates
	}
	return nil
}

func (x *Tenet) GetOutputs() map[string]*Output {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Tenet) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Tenet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Tenet) GetAssessment() *Assessment {
	if x != nil {
		return x.Assessment
	}
	return nil
}

type ChainedOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        string                 `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Tenet         string                 `protobuf:"bytes,2,opt,name=tenet,proto3" json:"tenet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainedOutput) Reset() {
	*x = ChainedOutput{}
	mi := &file_v1_policy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainedOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainedOutput) ProtoMessage() {}

func (x *ChainedOutput) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainedOutput.ProtoReflect.Descriptor instead.
func (*ChainedOutput) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{18}
}

func (x *ChainedOutput) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *ChainedOutput) GetTenet() string {
	if x != nil {
		return x.Tenet
	}
	return ""
}

// ChainedPredicate links a subject to another by extracting data from
// attestations of the first. The spec requires a `selector` to be executed
// by the specified `runtime` on an attestation of type `type`.
//
// The selector exec is expected to return either a hash string or a struct that
// looks like an in-toto resource descriptor which becomes the new effective
// subject during the evaluation.
type ChainedPredicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Runtime       string                 `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Identities    []*Identity            `protobuf:"bytes,5,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainedPredicate) Reset() {
	*x = ChainedPredicate{}
	mi := &file_v1_policy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainedPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainedPredicate) ProtoMessage() {}

func (x *ChainedPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainedPredicate.ProtoReflect.Descriptor instead.
func (*ChainedPredicate) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{19}
}

func (x *ChainedPredicate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChainedPredicate) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *ChainedPredicate) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *ChainedPredicate) GetIdentities() []*Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

type Assessment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assessment) Reset() {
	*x = Assessment{}
	mi := &file_v1_policy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assessment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assessment) ProtoMessage() {}

func (x *Assessment) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assessment.ProtoReflect.Descriptor instead.
func (*Assessment) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{20}
}

func (x *Assessment) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_v1_policy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{21}
}

func (x *Output) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Output) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// PolicyGroup captures the structure of a policy set in a
type PolicyGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Group identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Group metadata
	Meta *PolicyGroupMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	// Group reference
	Source *PolicyGroupRef `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Policy blocks modeling the group begaviour.
	Blocks        []*PolicyBlock `protobuf:"bytes,4,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyGroup) Reset() {
	*x = PolicyGroup{}
	mi := &file_v1_policy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyGroup) ProtoMessage() {}

func (x *PolicyGroup) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyGroup.ProtoReflect.Descriptor instead.
func (*PolicyGroup) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{22}
}

func (x *PolicyGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyGroup) GetMeta() *PolicyGroupMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PolicyGroup) GetSource() *PolicyGroupRef {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PolicyGroup) GetBlocks() []*PolicyBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// PolicyBlock groups policies in the PolicySet to apply properties to more
// than one policy at once.
type PolicyBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID string identifying the block
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// BlockMeta contains the metadata describing the
	Meta *BlockMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	// Policies is the list of policies grouped in the block
	Policies      []*Policy `protobuf:"bytes,3,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyBlock) Reset() {
	*x = PolicyBlock{}
	mi := &file_v1_policy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyBlock) ProtoMessage() {}

func (x *PolicyBlock) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyBlock.ProtoReflect.Descriptor instead.
func (*PolicyBlock) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{23}
}

func (x *PolicyBlock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyBlock) GetMeta() *BlockMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PolicyBlock) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

// GroupMeta is the metadata definition of a policy group
type PolicyGroupMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Description of the policy block
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Version of the group
	Version int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Control fronted by the policy group
	Controls []*Control `protobuf:"bytes,3,rep,name=controls,proto3" json:"controls,omitempty"`
	// Enforce the block (ON or OFF)
	Enforce string `protobuf:"bytes,4,opt,name=enforce,proto3" json:"enforce,omitempty"`
	// Expiration date of the policy group
	Expiration *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiration,proto3,oneof" json:"expiration,omitempty"`
	// Source of the group data when compiled from remote sources
	Origin        *v1.ResourceDescriptor `protobuf:"bytes,6,opt,name=origin,proto3,oneof" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyGroupMeta) Reset() {
	*x = PolicyGroupMeta{}
	mi := &file_v1_policy_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyGroupMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyGroupMeta) ProtoMessage() {}

func (x *PolicyGroupMeta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyGroupMeta.ProtoReflect.Descriptor instead.
func (*PolicyGroupMeta) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{24}
}

func (x *PolicyGroupMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PolicyGroupMeta) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyGroupMeta) GetControls() []*Control {
	if x != nil {
		return x.Controls
	}
	return nil
}

func (x *PolicyGroupMeta) GetEnforce() string {
	if x != nil {
		return x.Enforce
	}
	return ""
}

func (x *PolicyGroupMeta) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *PolicyGroupMeta) GetOrigin() *v1.ResourceDescriptor {
	if x != nil {
		return x.Origin
	}
	return nil
}

// BlockMeta defines the metadata definition of a policy block
type BlockMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Description of the policy block
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Assert mode to consider the policy block passing (OR or AND)
	AssertMode string `protobuf:"bytes,2,opt,name=assert_mode,json=assertMode,proto3" json:"assert_mode,omitempty"`
	// Enforce the block (ON or OFF)
	Enforce string `protobuf:"bytes,3,opt,name=enforce,proto3" json:"enforce,omitempty"`
	// Framework controls fronted by the block
	Controls      []*Control `protobuf:"bytes,4,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockMeta) Reset() {
	*x = BlockMeta{}
	mi := &file_v1_policy_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMeta) ProtoMessage() {}

func (x *BlockMeta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMeta.ProtoReflect.Descriptor instead.
func (*BlockMeta) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{25}
}

func (x *BlockMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BlockMeta) GetAssertMode() string {
	if x != nil {
		return x.AssertMode
	}
	return ""
}

func (x *BlockMeta) GetEnforce() string {
	if x != nil {
		return x.Enforce
	}
	return ""
}

func (x *BlockMeta) GetControls() []*Control {
	if x != nil {
		return x.Controls
	}
	return nil
}

// PolicyGroupRef references a group remotely
type PolicyGroupRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Group ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Pinned version of the group
	Version int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Expected identity when the group file is signed
	Identity *Identity `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	// Source location when referenced remotely
	Location      *v1.ResourceDescriptor `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyGroupRef) Reset() {
	*x = PolicyGroupRef{}
	mi := &file_v1_policy_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyGroupRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyGroupRef) ProtoMessage() {}

func (x *PolicyGroupRef) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyGroupRef.ProtoReflect.Descriptor instead.
func (*PolicyGroupRef) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{26}
}

func (x *PolicyGroupRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyGroupRef) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyGroupRef) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *PolicyGroupRef) GetLocation() *v1.ResourceDescriptor {
	if x != nil {
		return x.Location
	}
	return nil
}

var File_v1_policy_proto protoreflect.FileDescriptor

const file_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/policy.proto\x12\x13carabiner.policy.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a0in_toto_attestation/v1/resource_descriptor.proto\"\xba\x02\n" +
	"\tPolicySet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x04meta\x18\x02 \x01(\v2\".carabiner.policy.v1.PolicySetMetaR\x04meta\x12<\n" +
	"\x06common\x18\x03 \x01(\v2$.carabiner.policy.v1.PolicySetCommonR\x06common\x127\n" +
	"\bpolicies\x18\x04 \x03(\v2\x1b.carabiner.policy.v1.PolicyR\bpolicies\x124\n" +
	"\x05chain\x18\x05 \x03(\v2\x1e.carabiner.policy.v1.ChainLinkR\x05chain\x128\n" +
	"\x06groups\x18\x06 \x03(\v2 .carabiner.policy.v1.PolicyGroupR\x06groups\"\xd2\x02\n" +
	"\rPolicySetMeta\x12\x18\n" +
	"\aruntime\x18\x01 \x01(\tR\aruntime\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12:\n" +
	"\n" +
	"expiration\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x18\n" +
	"\aenforce\x18\x05 \x01(\tR\aenforce\x12A\n" +
	"\n" +
	"frameworks\x18\x06 \x03(\v2!.carabiner.policy.v1.FrameworkRefR\n" +
	"frameworks\x12G\n" +
	"\x06origin\x18\a \x01(\v2*.in_toto_attestation.v1.ResourceDescriptorH\x00R\x06origin\x88\x01\x01B\t\n" +
	"\a_origin\"~\n" +
	"\fFrameworkRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12J\n" +
	"\n" +
	"definition\x18\x03 \x01(\v2*.in_toto_attestation.v1.ResourceDescriptorR\n" +
	"definition\"\xba\x02\n" +
	"\x0fPolicySetCommon\x12=\n" +
	"\n" +
	"identities\x18\x01 \x03(\v2\x1d.carabiner.policy.v1.IdentityR\n" +
	"identities\x12>\n" +
	"\n" +
	"references\x18\x02 \x03(\v2\x1e.carabiner.policy.v1.PolicyRefR\n" +
	"references\x12K\n" +
	"\acontext\x18\x03 \x03(\v21.carabiner.policy.v1.PolicySetCommon.ContextEntryR\acontext\x1a[\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.carabiner.policy.v1.ContextValR\x05value:\x028\x01\"\xd3\x04\n" +
	"\x06Policy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x06source\x18\x02 \x01(\v2\x1e.carabiner.policy.v1.PolicyRefR\x06source\x12-\n" +
	"\x04meta\x18\x03 \x01(\v2\x19.carabiner.policy.v1.MetaR\x04meta\x12B\n" +
	"\acontext\x18\x04 \x03(\v2(.carabiner.policy.v1.Policy.ContextEntryR\acontext\x124\n" +
	"\x05chain\x18\x05 \x03(\v2\x1e.carabiner.policy.v1.ChainLinkR\x05chain\x12=\n" +
	"\n" +
	"identities\x18\x06 \x03(\v2\x1d.carabiner.policy.v1.IdentityR\n" +
	"identities\x12B\n" +
	"\n" +
	"predicates\x18\a \x01(\v2\".carabiner.policy.v1.PredicateSpecR\n" +
	"predicates\x12D\n" +
	"\ftransformers\x18\b \x03(\v2 .carabiner.policy.v1.TransformerR\ftransformers\x122\n" +
	"\x06tenets\x18\t \x03(\v2\x1a.carabiner.policy.v1.TenetR\x06tenets\x1a[\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.carabiner.policy.v1.ContextValR\x05value:\x028\x01\"\xb8\x01\n" +
	"\tPolicyRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x129\n" +
	"\bidentity\x18\x03 \x01(\v2\x1d.carabiner.policy.v1.IdentityR\bidentity\x12F\n" +
	"\blocation\x18\x04 \x01(\v2*.in_toto_attestation.v1.ResourceDescriptorR\blocation\"\\\n" +
	"\tChainLink\x12E\n" +
	"\tpredicate\x18\x01 \x01(\v2%.carabiner.policy.v1.ChainedPredicateH\x00R\tpredicateB\b\n" +
	"\x06source\"\xf5\x02\n" +
	"\x04Meta\x12\x18\n" +
	"\aruntime\x18\x01 \x01(\tR\aruntime\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vassert_mode\x18\x03 \x01(\tR\n" +
	"assertMode\x128\n" +
	"\bcontrols\x18\x04 \x03(\v2\x1c.carabiner.policy.v1.ControlR\bcontrols\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12\x18\n" +
	"\aenforce\x18\x06 \x01(\tR\aenforce\x12?\n" +
	"\n" +
	"expiration\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"expiration\x88\x01\x01\x12G\n" +
	"\x06origin\x18\b \x01(\v2*.in_toto_attestation.v1.ResourceDescriptorH\x01R\x06origin\x88\x01\x01B\r\n" +
	"\v_expirationB\t\n" +
	"\a_origin\"\xf1\x01\n" +
	"\bIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12F\n" +
	"\bsigstore\x18\x02 \x01(\v2%.carabiner.policy.v1.IdentitySigstoreH\x00R\bsigstore\x88\x01\x01\x127\n" +
	"\x03key\x18\x03 \x01(\v2 .carabiner.policy.v1.IdentityKeyH\x01R\x03key\x88\x01\x01\x127\n" +
	"\x03ref\x18\x04 \x01(\v2 .carabiner.policy.v1.IdentityRefH\x02R\x03ref\x88\x01\x01B\v\n" +
	"\t_sigstoreB\x06\n" +
	"\x04_keyB\x06\n" +
	"\x04_ref\"c\n" +
	"\aControl\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12\x1c\n" +
	"\tframework\x18\x03 \x01(\tR\tframework\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"h\n" +
	"\x10IdentitySigstore\x12\x17\n" +
	"\x04mode\x18\x01 \x01(\tH\x00R\x04mode\x88\x01\x01\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\tR\bidentityB\a\n" +
	"\x05_mode\"E\n" +
	"\vIdentityKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"\x1d\n" +
	"\vIdentityRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x85\x02\n" +
	"\n" +
	"ContextVal\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\brequired\x18\x02 \x01(\bH\x00R\brequired\x88\x01\x01\x121\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueH\x01R\x05value\x88\x01\x01\x125\n" +
	"\adefault\x18\x04 \x01(\v2\x16.google.protobuf.ValueH\x02R\adefault\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01B\v\n" +
	"\t_requiredB\b\n" +
	"\x06_valueB\n" +
	"\n" +
	"\b_defaultB\x0e\n" +
	"\f_description\"=\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1a\n" +
	"\bguidance\x18\x02 \x01(\tR\bguidance\"\x1d\n" +
	"\vTransformer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\rPredicateSpec\x12\x14\n" +
	"\x05types\x18\x01 \x03(\tR\x05types\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xae\x03\n" +
	"\x05Tenet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12B\n" +
	"\n" +
	"predicates\x18\x04 \x01(\v2\".carabiner.policy.v1.PredicateSpecR\n" +
	"predicates\x12A\n" +
	"\aoutputs\x18\x05 \x03(\v2'.carabiner.policy.v1.Tenet.OutputsEntryR\aoutputs\x120\n" +
	"\x05error\x18\x06 \x01(\v2\x1a.carabiner.policy.v1.ErrorR\x05error\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12?\n" +
	"\n" +
	"assessment\x18\b \x01(\v2\x1f.carabiner.policy.v1.AssessmentR\n" +
	"assessment\x1aW\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.carabiner.policy.v1.OutputR\x05value:\x028\x01\"=\n" +
	"\rChainedOutput\x12\x16\n" +
	"\x06policy\x18\x01 \x01(\tR\x06policy\x12\x14\n" +
	"\x05tenet\x18\x02 \x01(\tR\x05tenet\"\x9b\x01\n" +
	"\x10ChainedPredicate\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x12=\n" +
	"\n" +
	"identities\x18\x05 \x03(\v2\x1d.carabiner.policy.v1.IdentityR\n" +
	"identities\"&\n" +
	"\n" +
	"Assessment\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"J\n" +
	"\x06Output\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value\"\xce\x01\n" +
	"\vPolicyGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\x04meta\x18\x02 \x01(\v2$.carabiner.policy.v1.PolicyGroupMetaR\x04meta\x12;\n" +
	"\x06source\x18\x03 \x01(\v2#.carabiner.policy.v1.PolicyGroupRefR\x06source\x128\n" +
	"\x06blocks\x18\x04 \x03(\v2 .carabiner.policy.v1.PolicyBlockR\x06blocks\"\x8a\x01\n" +
	"\vPolicyBlock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x04meta\x18\x02 \x01(\v2\x1e.carabiner.policy.v1.BlockMetaR\x04meta\x127\n" +
	"\bpolicies\x18\x03 \x03(\v2\x1b.carabiner.policy.v1.PolicyR\bpolicies\"\xc5\x02\n" +
	"\x0fPolicyGroupMeta\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x128\n" +
	"\bcontrols\x18\x03 \x03(\v2\x1c.carabiner.policy.v1.ControlR\bcontrols\x12\x18\n" +
	"\aenforce\x18\x04 \x01(\tR\aenforce\x12?\n" +
	"\n" +
	"expiration\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"expiration\x88\x01\x01\x12G\n" +
	"\x06origin\x18\x06 \x01(\v2*.in_toto_attestation.v1.ResourceDescriptorH\x01R\x06origin\x88\x01\x01B\r\n" +
	"\v_expirationB\t\n" +
	"\a_origin\"\xa2\x01\n" +
	"\tBlockMeta\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1f\n" +
	"\vassert_mode\x18\x02 \x01(\tR\n" +
	"assertMode\x12\x18\n" +
	"\aenforce\x18\x03 \x01(\tR\aenforce\x128\n" +
	"\bcontrols\x18\x04 \x03(\v2\x1c.carabiner.policy.v1.ControlR\bcontrols\"\xbd\x01\n" +
	"\x0ePolicyGroupRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x129\n" +
	"\bidentity\x18\x03 \x01(\v2\x1d.carabiner.policy.v1.IdentityR\bidentity\x12F\n" +
	"\blocation\x18\x04 \x01(\v2*.in_toto_attestation.v1.ResourceDescriptorR\blocationB\xbc\x01\n" +
	"\x17com.carabiner.policy.v1B\vPolicyProtoP\x01Z&github.com/carabiner-dev/policy/api/v1\xa2\x02\x03CPX\xaa\x02\x13Carabiner.Policy.V1\xca\x02\x13Carabiner\\Policy\\V1\xe2\x02\x1fCarabiner\\Policy\\V1\\GPBMetadata\xea\x02\x15Carabiner::Policy::V1b\x06proto3"

var (
	file_v1_policy_proto_rawDescOnce sync.Once
	file_v1_policy_proto_rawDescData []byte
)

func file_v1_policy_proto_rawDescGZIP() []byte {
	file_v1_policy_proto_rawDescOnce.Do(func() {
		file_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_policy_proto_rawDesc), len(file_v1_policy_proto_rawDesc)))
	})
	return file_v1_policy_proto_rawDescData
}

var file_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_v1_policy_proto_goTypes = []any{
	(*PolicySet)(nil),             // 0: carabiner.policy.v1.PolicySet
	(*PolicySetMeta)(nil),         // 1: carabiner.policy.v1.PolicySetMeta
	(*FrameworkRef)(nil),          // 2: carabiner.policy.v1.FrameworkRef
	(*PolicySetCommon)(nil),       // 3: carabiner.policy.v1.PolicySetCommon
	(*Policy)(nil),                // 4: carabiner.policy.v1.Policy
	(*PolicyRef)(nil),             // 5: carabiner.policy.v1.PolicyRef
	(*ChainLink)(nil),             // 6: carabiner.policy.v1.ChainLink
	(*Meta)(nil),                  // 7: carabiner.policy.v1.Meta
	(*Identity)(nil),              // 8: carabiner.policy.v1.Identity
	(*Control)(nil),               // 9: carabiner.policy.v1.Control
	(*IdentitySigstore)(nil),      // 10: carabiner.policy.v1.IdentitySigstore
	(*IdentityKey)(nil),           // 11: carabiner.policy.v1.IdentityKey
	(*IdentityRef)(nil),           // 12: carabiner.policy.v1.IdentityRef
	(*ContextVal)(nil),            // 13: carabiner.policy.v1.ContextVal
	(*Error)(nil),                 // 14: carabiner.policy.v1.Error
	(*Transformer)(nil),           // 15: carabiner.policy.v1.Transformer
	(*PredicateSpec)(nil),         // 16: carabiner.policy.v1.PredicateSpec
	(*Tenet)(nil),                 // 17: carabiner.policy.v1.Tenet
	(*ChainedOutput)(nil),         // 18: carabiner.policy.v1.ChainedOutput
	(*ChainedPredicate)(nil),      // 19: carabiner.policy.v1.ChainedPredicate
	(*Assessment)(nil),            // 20: carabiner.policy.v1.Assessment
	(*Output)(nil),                // 21: carabiner.policy.v1.Output
	(*PolicyGroup)(nil),           // 22: carabiner.policy.v1.PolicyGroup
	(*PolicyBlock)(nil),           // 23: carabiner.policy.v1.PolicyBlock
	(*PolicyGroupMeta)(nil),       // 24: carabiner.policy.v1.PolicyGroupMeta
	(*BlockMeta)(nil),             // 25: carabiner.policy.v1.BlockMeta
	(*PolicyGroupRef)(nil),        // 26: carabiner.policy.v1.PolicyGroupRef
	nil,                           // 27: carabiner.policy.v1.PolicySetCommon.ContextEntry
	nil,                           // 28: carabiner.policy.v1.Policy.ContextEntry
	nil,                           // 29: carabiner.policy.v1.Tenet.OutputsEntry
	(*timestamppb.Timestamp)(nil), // 30: google.protobuf.Timestamp
	(*v1.ResourceDescriptor)(nil), // 31: in_toto_attestation.v1.ResourceDescriptor
	(*structpb.Value)(nil),        // 32: google.protobuf.Value
}
var file_v1_policy_proto_depIdxs = []int32{
	1,  // 0: carabiner.policy.v1.PolicySet.meta:type_name -> carabiner.policy.v1.PolicySetMeta
	3,  // 1: carabiner.policy.v1.PolicySet.common:type_name -> carabiner.policy.v1.PolicySetCommon
	4,  // 2: carabiner.policy.v1.PolicySet.policies:type_name -> carabiner.policy.v1.Policy
	6,  // 3: carabiner.policy.v1.PolicySet.chain:type_name -> carabiner.policy.v1.ChainLink
	22, // 4: carabiner.policy.v1.PolicySet.groups:type_name -> carabiner.policy.v1.PolicyGroup
	30, // 5: carabiner.policy.v1.PolicySetMeta.expiration:type_name -> google.protobuf.Timestamp
	2,  // 6: carabiner.policy.v1.PolicySetMeta.frameworks:type_name -> carabiner.policy.v1.FrameworkRef
	31, // 7: carabiner.policy.v1.PolicySetMeta.origin:type_name -> in_toto_attestation.v1.ResourceDescriptor
	31, // 8: carabiner.policy.v1.FrameworkRef.definition:type_name -> in_toto_attestation.v1.ResourceDescriptor
	8,  // 9: carabiner.policy.v1.PolicySetCommon.identities:type_name -> carabiner.policy.v1.Identity
	5,  // 10: carabiner.policy.v1.PolicySetCommon.references:type_name -> carabiner.policy.v1.PolicyRef
	27, // 11: carabiner.policy.v1.PolicySetCommon.context:type_name -> carabiner.policy.v1.PolicySetCommon.ContextEntry
	5,  // 12: carabiner.policy.v1.Policy.source:type_name -> carabiner.policy.v1.PolicyRef
	7,  // 13: carabiner.policy.v1.Policy.meta:type_name -> carabiner.policy.v1.Meta
	28, // 14: carabiner.policy.v1.Policy.context:type_name -> carabiner.policy.v1.Policy.ContextEntry
	6,  // 15: carabiner.policy.v1.Policy.chain:type_name -> carabiner.policy.v1.ChainLink
	8,  // 16: carabiner.policy.v1.Policy.identities:type_name -> carabiner.policy.v1.Identity
	16, // 17: carabiner.policy.v1.Policy.predicates:type_name -> carabiner.policy.v1.PredicateSpec
	15, // 18: carabiner.policy.v1.Policy.transformers:type_name -> carabiner.policy.v1.Transformer
	17, // 19: carabiner.policy.v1.Policy.tenets:type_name -> carabiner.policy.v1.Tenet
	8,  // 20: carabiner.policy.v1.PolicyRef.identity:type_name -> carabiner.policy.v1.Identity
	31, // 21: carabiner.policy.v1.PolicyRef.location:type_name -> in_toto_attestation.v1.ResourceDescriptor
	19, // 22: carabiner.policy.v1.ChainLink.predicate:type_name -> carabiner.policy.v1.ChainedPredicate
	9,  // 23: carabiner.policy.v1.Meta.controls:type_name -> carabiner.policy.v1.Control
	30, // 24: carabiner.policy.v1.Meta.expiration:type_name -> google.protobuf.Timestamp
	31, // 25: carabiner.policy.v1.Meta.origin:type_name -> in_toto_attestation.v1.ResourceDescriptor
	10, // 26: carabiner.policy.v1.Identity.sigstore:type_name -> carabiner.policy.v1.IdentitySigstore
	11, // 27: carabiner.policy.v1.Identity.key:type_name -> carabiner.policy.v1.IdentityKey
	12, // 28: carabiner.policy.v1.Identity.ref:type_name -> carabiner.policy.v1.IdentityRef
	32, // 29: carabiner.policy.v1.ContextVal.value:type_name -> google.protobuf.Value
	32, // 30: carabiner.policy.v1.ContextVal.default:type_name -> google.protobuf.Value
	16, // 31: carabiner.policy.v1.Tenet.predicates:type_name -> carabiner.policy.v1.PredicateSpec
	29, // 32: carabiner.policy.v1.Tenet.outputs:type_name -> carabiner.policy.v1.Tenet.OutputsEntry
	14, // 33: carabiner.policy.v1.Tenet.error:type_name -> carabiner.policy.v1.Error
	20, // 34: carabiner.policy.v1.Tenet.assessment:type_name -> carabiner.policy.v1.Assessment
	8,  // 35: carabiner.policy.v1.ChainedPredicate.identities:type_name -> carabiner.policy.v1.Identity
	32, // 36: carabiner.policy.v1.Output.value:type_name -> google.protobuf.Value
	24, // 37: carabiner.policy.v1.PolicyGroup.meta:type_name -> carabiner.policy.v1.PolicyGroupMeta
	26, // 38: carabiner.policy.v1.PolicyGroup.source:type_name -> carabiner.policy.v1.PolicyGroupRef
	23, // 39: carabiner.policy.v1.PolicyGroup.blocks:type_name -> carabiner.policy.v1.PolicyBlock
	25, // 40: carabiner.policy.v1.PolicyBlock.meta:type_name -> carabiner.policy.v1.BlockMeta
	4,  // 41: carabiner.policy.v1.PolicyBlock.policies:type_name -> carabiner.policy.v1.Policy
	9,  // 42: carabiner.policy.v1.PolicyGroupMeta.controls:type_name -> carabiner.policy.v1.Control
	30, // 43: carabiner.policy.v1.PolicyGroupMeta.expiration:type_name -> google.protobuf.Timestamp
	31, // 44: carabiner.policy.v1.PolicyGroupMeta.origin:type_name -> in_toto_attestation.v1.ResourceDescriptor
	9,  // 45: carabiner.policy.v1.BlockMeta.controls:type_name -> carabiner.policy.v1.Control
	8,  // 46: carabiner.policy.v1.PolicyGroupRef.identity:type_name -> carabiner.policy.v1.Identity
	31, // 47: carabiner.policy.v1.PolicyGroupRef.location:type_name -> in_toto_attestation.v1.ResourceDescriptor
	13, // 48: carabiner.policy.v1.PolicySetCommon.ContextEntry.value:type_name -> carabiner.policy.v1.ContextVal
	13, // 49: carabiner.policy.v1.Policy.ContextEntry.value:type_name -> carabiner.policy.v1.ContextVal
	21, // 50: carabiner.policy.v1.Tenet.OutputsEntry.value:type_name -> carabiner.policy.v1.Output
	51, // [51:51] is the sub-list for method output_type
	51, // [51:51] is the sub-list for method input_type
	51, // [51:51] is the sub-list for extension type_name
	51, // [51:51] is the sub-list for extension extendee
	0,  // [0:51] is the sub-list for field type_name
}

func init() { file_v1_policy_proto_init() }
func file_v1_policy_proto_init() {
	if File_v1_policy_proto != nil {
		return
	}
	file_v1_policy_proto_msgTypes[1].OneofWrappers = []any{}
	file_v1_policy_proto_msgTypes[6].OneofWrappers = []any{
		(*ChainLink_Predicate)(nil),
	}
	file_v1_policy_proto_msgTypes[7].OneofWrappers = []any{}
	file_v1_policy_proto_msgTypes[8].OneofWrappers = []any{}
	file_v1_policy_proto_msgTypes[10].OneofWrappers = []any{}
	file_v1_policy_proto_msgTypes[13].OneofWrappers = []any{}
	file_v1_policy_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_policy_proto_rawDesc), len(file_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_policy_proto_goTypes,
		DependencyIndexes: file_v1_policy_proto_depIdxs,
		MessageInfos:      file_v1_policy_proto_msgTypes,
	}.Build()
	File_v1_policy_proto = out.File
	file_v1_policy_proto_goTypes = nil
	file_v1_policy_proto_depIdxs = nil
}
